### ISSUE TITLE
Fail to compile when trying to include <optional> 

### ISSUE THREAD

**Issue by clouserw** [ChaseCares/AirGradient-InfluxDB#13]
To reproduce:

1) Using Arduino IDE 2.0.1
2) Press "compile" button and get failure:

```
 fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.

exit status 1

Compilation error: optional: No such file or directory
```

**Comment by ChaseCares** [comment]
Hello! Sorry I missed your issue, did you end up getting it fixed?

 edit:  Okay, so I just went through and compiled everything from scratch/clean install, and didn't run into any issues. Will you make sure that your gcc compiler is up to date.

**Comment by clouserw** [comment]
Howdy.  I ended up writing my own and am not in a position to test this anymore.  If you can't reproduce I think we should close it.  Thanks
