### ISSUE TITLE
Occasional eroneous CO2 values

### ISSUE THREAD

**Issue by ChaseCares** [ChaseCares/AirGradient-InfluxDB#9]
Occasionally there is a -1 value that shows up in the DB. Although this can be filtered out, if this is a widespread issue some form of mitigation should be created.

![example](https://user-images.githubusercontent.com/13863948/141487662-9c49c8d1-d56f-41f1-8ef7-fbe84d73df05.png)

**Comment by ChaseCares** [comment]
If you're having this issue please react with a 👍 on this comment.

**Comment by horknfbr** [comment]
commit 342e1d30ceb5b940fab6ee2db19707e819a342fb fixed this issue for me
